version: '3'  

 # Define services that will be part of the Docker Compose deployment
services: 
  app:  
    build: .
    ports:  
      - "8000:8000"  # Map port 8000 of the container to port 8000 of the host (FastAPI will run on this port)
    restart: unless-stopped

